server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
#  zipkin:
#    base-url: http://localhost:9411/  #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1  #采样的百分比
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds.aliyuncs.com:3306/springcloudalibaba?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: CyPde666
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719 #跟控制台交流的端口,随意指定一个未使用的端口即可
#        dashboard: localhost:8858 # 指定控制台服务的地址
#        clientIp: 172.17.0.3
        dashboard: localhost:8858
#      filter:
#        enabled: false

service-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: localhost:9876 #rocketMQ服务的地址
  producer:
    group: shop-order # 生产者组